name: mpesa_sdk
description: Tanzania Open API Library SDK
version: 0.0.1+1
repository: https://github.com/mghase/mpesa_sdk
homepage: https://github.com/mghase/mpesa_sdk

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  basic_utils: ^4.2.2
  dio: ^4.0.6
  pointycastle: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


